import Link from "next/link";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import { formatBelgianDate } from "@/lib/fotografie/date";
import styles from "./photography-admin.module.css";
export const dynamic = "force-dynamic";
export default async function PhotographyAdmin(){
 let galleries:any[]=[]; let errorMessage="";
 try{const {data,error}=await getSupabaseAdmin().from("photo_galleries").select("id,title,slug,shoot_date,status,client_name,share_token").order("shoot_date",{ascending:false}); if(error) errorMessage=error.message; else galleries=data??[];}catch(error){errorMessage=error instanceof Error?error.message:"Onbekende fout"}
 return <main className={styles.page}><div className={styles.shell}><aside className={styles.side}><div className={styles.logo}>SaGo<small>Photography</small></div><nav className={styles.nav}><Link href="/admin/fotografie"><span>▧</span>Galerijen</Link><Link href="#"><span>♙</span>Klanten</Link><Link href="/admin/fotografie/galerijen/nieuw"><span>⇧</span>Uploads</Link><Link href="#"><span>⚙</span>Instellingen</Link></nav><div className={styles.help}><strong>Hulp nodig?</strong>De galerijmodule wordt stap voor stap opgebouwd.</div></aside><section className={styles.main}><header className={styles.top}><div><h1>Galerijen</h1><p>Beheer en organiseer al je klantengalerijen op één plek.</p></div><Link className={styles.cta} href="/admin/fotografie/galerijen/nieuw">＋ Nieuwe galerij</Link></header><div className={styles.stats}><div className={styles.stat}><strong>{galleries.length}</strong><span>Totaal galerijen</span></div><div className={styles.stat}><strong>{galleries.filter(g=>g.status==='active').length}</strong><span>Actief</span></div><div className={styles.stat}><strong>{new Set(galleries.map(g=>g.client_name).filter(Boolean)).size}</strong><span>Klanten</span></div><div className={styles.stat}><strong>{galleries.filter(g=>g.share_token).length}</strong><span>Deelbare links</span></div></div>{errorMessage&&<section className={styles.error}><h2>De galerijen zijn nog niet gekoppeld</h2><p>De interface werkt, maar de Supabase-tabellen moeten nog één keer aangemaakt worden.</p><code>{errorMessage}</code></section>}{!errorMessage&&galleries.length===0&&<section className={styles.empty}><div className={styles.emptyIcon}>♡</div><h2>Je hebt nog geen galerijen</h2><p>Maak je eerste klantengalerij aan en deel mooie herinneringen veilig met een familie.</p><Link className={styles.cta} href="/admin/fotografie/galerijen/nieuw">＋ Nieuwe galerij aanmaken</Link></section>}<div className={styles.cards}>{galleries.map(g=><article className={styles.card} key={g.id}><small>{g.status}</small><h2>{g.title}</h2><p>{g.client_name||'Geen klantnaam'} · {g.shoot_date?formatBelgianDate(g.shoot_date):'Geen datum'}</p><div className={styles.links}><Link href={`/admin/fotografie/galerijen/${g.id}`}>Bewerken</Link><Link target="_blank" href={`/fotografie/galerij/${g.slug}?token=${g.share_token}`}>Bekijken</Link></div></article>)}</div></section></div></main>
}
