export type FrenchExerciseCategory =
  | "woordenschat"
  | "grammatica"
  | "lezen"
  | "luisteren"
  | "schrijven"
  | "spreken"
  | "cultuur";

export type FrenchExerciseType =
  | "multiple-choice"
  | "text"
  | "open"
  | "listening";

export type FrenchDifficulty = 1 | 2 | 3;

export type FrenchExercise = {
  id: string;
  title: string;
  instruction: string;
  category: FrenchExerciseCategory;
  type: FrenchExerciseType;
  difficulty: FrenchDifficulty;
  learningGoal: string;
  options?: string[];
  answer?: string | string[];
  explanation?: string;
  hint?: string;
  audioText?: string;
  audioSpeaker?: {
    name: string;
    gender: "female" | "male";
  };
  example?: string;
  minimumWords?: number;
};

export type FrenchPreparationSection = {
  id: FrenchExerciseCategory;
  title: string;
  description: string;
  icon: "chat" | "book" | "headphones" | "pen" | "mic" | "globe" | "blocks";
};

export const frenchPreparationExercises: FrenchExercise[] = [
  {
    id: "vocab-1",
    title: "Begroeten",
    instruction: "Welke begroeting gebruik je meestal overdag?",
    category: "woordenschat",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik herken en gebruik eenvoudige begroetingen.",
    options: ["Bonsoir", "Bonjour", "Bonne nuit", "Au revoir"],
    answer: "Bonjour",
    hint: "Denk aan de begroeting die je vanaf de ochtend tot de late namiddag gebruikt.",
    explanation: "Bonjour betekent goedendag en gebruik je overdag.",
  },
  {
    id: "vocab-2",
    title: "Jezelf voorstellen",
    instruction: "Vul aan: Je ... Emma.",
    category: "woordenschat",
    type: "text",
    difficulty: 1,
    learningGoal: "Ik kan mijn naam in het Frans zeggen.",
    answer: ["m'appelle", "m’appelle"],
    hint: "De volledige uitdrukking voor ‘ik heet’ begint met Je m’...",
    explanation: "Je m'appelle betekent: ik heet.",
  },
  {
    id: "vocab-3",
    title: "Leeftijd zeggen",
    instruction: "Hoe zeg je: Ik ben elf jaar?",
    category: "woordenschat",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik kan mijn leeftijd zeggen.",
    options: ["Je suis onze ans.", "J'ai onze ans.", "Je vais onze ans.", "Je fais onze ans."],
    answer: "J'ai onze ans.",
    hint: "In het Frans ‘heb’ je een leeftijd.",
    explanation: "Voor een leeftijd gebruikt het Frans avoir: J'ai onze ans.",
  },
  {
    id: "vocab-4",
    title: "Schoolmateriaal",
    instruction: "Wat betekent une trousse?",
    category: "woordenschat",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik begrijp basiswoorden uit de klas.",
    options: ["een boekentas", "een pennenzak", "een schrift", "een meetlat"],
    answer: "een pennenzak",
    hint: "Je bewaart er pennen en potloden in.",
    explanation: "Une trousse is een pennenzak.",
  },
  {
    id: "vocab-5",
    title: "Dagen van de week",
    instruction: "Welke dag komt na mardi?",
    category: "woordenschat",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik ken de dagen van de week.",
    options: ["lundi", "mercredi", "jeudi", "vendredi"],
    answer: "mercredi",
    hint: "Mardi is dinsdag.",
    explanation: "Na mardi komt mercredi.",
  },
  {
    id: "vocab-6",
    title: "Getallen tot twintig",
    instruction: "Schrijf 14 in het Frans.",
    category: "woordenschat",
    type: "text",
    difficulty: 1,
    learningGoal: "Ik schrijf getallen tot twintig.",
    answer: "quatorze",
    hint: "Het woord begint met qua-.",
    explanation: "14 schrijf je als quatorze.",
  },
  {
    id: "vocab-7",
    title: "Familie",
    instruction: "Wat betekent mon frère?",
    category: "woordenschat",
    type: "multiple-choice",
    difficulty: 2,
    learningGoal: "Ik begrijp basiswoorden over familie.",
    options: ["mijn vader", "mijn broer", "mijn neef", "mijn opa"],
    answer: "mijn broer",
    hint: "Frère is een mannelijk familielid van dezelfde generatie.",
    explanation: "Mon frère betekent mijn broer.",
  },
  {
    id: "vocab-8",
    title: "Uur en moment",
    instruction: "Wat betekent Il est huit heures et quart?",
    category: "woordenschat",
    type: "multiple-choice",
    difficulty: 2,
    learningGoal: "Ik begrijp eenvoudige tijdsaanduidingen.",
    options: ["Het is 7.45 uur.", "Het is 8.00 uur.", "Het is 8.15 uur.", "Het is 8.30 uur."],
    answer: "Het is 8.15 uur.",
    hint: "Et quart betekent een kwartier erbij.",
    explanation: "Huit heures et quart is kwart over acht.",
  },

  {
    id: "gram-1",
    title: "Lidwoord voor klinker",
    instruction: "Kies het juiste lidwoord: ... école.",
    category: "grammatica",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik kies een passend bepaald lidwoord.",
    options: ["le", "la", "l'", "les"],
    answer: "l'",
    hint: "École begint met een klinker.",
    explanation: "Voor een enkelvoudig woord dat met een klinker begint, gebruik je l'.",
  },
  {
    id: "gram-2",
    title: "Meervoud",
    instruction: "Wat is het bepaalde meervoud van un livre?",
    category: "grammatica",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik vorm een regelmatig meervoud.",
    options: ["des livre", "les livres", "un livres", "le livres"],
    answer: "les livres",
    hint: "Gebruik het bepaalde meervoudslidwoord en voeg meestal -s toe.",
    explanation: "Het bepaalde meervoud is les livres.",
  },
  {
    id: "gram-3",
    title: "Être",
    instruction: "Vul aan: Nous ... à l'école.",
    category: "grammatica",
    type: "text",
    difficulty: 1,
    learningGoal: "Ik gebruik de tegenwoordige tijd van être.",
    answer: "sommes",
    hint: "De vorm bij nous begint met s-.",
    explanation: "Nous sommes betekent wij zijn.",
  },
  {
    id: "gram-4",
    title: "Avoir",
    instruction: "Vul aan: Ils ... un chien.",
    category: "grammatica",
    type: "text",
    difficulty: 1,
    learningGoal: "Ik gebruik de tegenwoordige tijd van avoir.",
    answer: "ont",
    hint: "De vorm bij ils bestaat uit drie letters.",
    explanation: "Ils ont betekent zij hebben.",
  },
  {
    id: "gram-5",
    title: "Ontkenning",
    instruction: "Maak ontkennend: J'aime le chocolat.",
    category: "grammatica",
    type: "text",
    difficulty: 2,
    learningGoal: "Ik maak een eenvoudige zin ontkennend.",
    answer: ["je n'aime pas le chocolat", "je n’aime pas le chocolat"],
    hint: "Zet ne/n’ vóór de persoonsvorm en pas erna.",
    explanation: "De ontkenning staat rond het werkwoord: Je n'aime pas le chocolat.",
  },
  {
    id: "gram-6",
    title: "Bijvoeglijk naamwoord",
    instruction: "Kies de juiste vorm: une ... fille.",
    category: "grammatica",
    type: "multiple-choice",
    difficulty: 2,
    learningGoal: "Ik laat een eenvoudig bijvoeglijk naamwoord overeenkomen.",
    options: ["petit", "petite", "petits", "petites"],
    answer: "petite",
    hint: "Fille is vrouwelijk enkelvoud.",
    explanation: "Bij vrouwelijk enkelvoud gebruik je petite.",
  },
  {
    id: "gram-7",
    title: "Regelmatig werkwoord op -er",
    instruction: "Vul aan: Tu ... au football. (jouer)",
    category: "grammatica",
    type: "text",
    difficulty: 2,
    learningGoal: "Ik vervoeg een regelmatig werkwoord op -er.",
    answer: "joues",
    hint: "Neem de stam jou- en gebruik de uitgang bij tu.",
    explanation: "Bij tu krijgt een regelmatig -er-werkwoord de uitgang -es: tu joues.",
  },
  {
    id: "gram-8",
    title: "Vraagzin",
    instruction: "Maak een eenvoudige vraag met est-ce que: Tu aimes le sport.",
    category: "grammatica",
    type: "text",
    difficulty: 3,
    learningGoal: "Ik maak een eenvoudige Franse vraagzin.",
    answer: ["est-ce que tu aimes le sport", "est ce que tu aimes le sport"],
    hint: "Zet est-ce que voor de gewone mededelende zin.",
    explanation: "Een correcte vraag is: Est-ce que tu aimes le sport?",
  },

  {
    id: "read-1",
    title: "Camille stelt zich voor",
    instruction: "Lees: « Je m'appelle Camille. J'ai onze ans. J'habite à Lille. J'aime le tennis et les crêpes. » Waar woont Camille?",
    category: "lezen",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik haal expliciete informatie uit een korte tekst.",
    options: ["à Paris", "à Lille", "à Bruxelles", "à Liège"],
    answer: "à Lille",
    hint: "Zoek de zin met J'habite.",
    explanation: "In de tekst staat: J'habite à Lille.",
  },
  {
    id: "read-2",
    title: "De schooldag",
    instruction: "Lees: « Le lundi, Hugo a français à neuf heures. À dix heures, il a mathématiques. » Welk vak heeft Hugo om negen uur?",
    category: "lezen",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik begrijp een eenvoudig uurrooster.",
    options: ["wiskunde", "Frans", "geschiedenis", "sport"],
    answer: "Frans",
    hint: "Neuf heures betekent negen uur.",
    explanation: "Om negen uur heeft Hugo Frans.",
  },
  {
    id: "read-3",
    title: "In de kantine",
    instruction: "Lees: « À midi, Zoé mange une soupe, du pain et une pomme. Elle boit de l'eau. » Wat drinkt Zoé?",
    category: "lezen",
    type: "text",
    difficulty: 1,
    learningGoal: "Ik begrijp eenvoudige informatie over eten en drinken.",
    answer: ["de l'eau", "de l’eau", "water"],
    hint: "Zoek de woorden na Elle boit.",
    explanation: "Zoé drinkt de l'eau: water.",
  },
  {
    id: "read-4",
    title: "Een bericht begrijpen",
    instruction: "Lees: « Salut Noor! Le cours de français commence demain à 8 h 30 dans la salle 12. N'oublie pas ton cahier. » Wat moet Noor meenemen?",
    category: "lezen",
    type: "multiple-choice",
    difficulty: 2,
    learningGoal: "Ik begrijp praktische informatie in een kort bericht.",
    options: ["haar boekentas", "haar schrift", "haar lunch", "haar sportkleren"],
    answer: "haar schrift",
    hint: "Cahier betekent schrift.",
    explanation: "N'oublie pas ton cahier betekent: vergeet je schrift niet.",
  },
  {
    id: "read-5",
    title: "Hoofdgedachte",
    instruction: "Lees: « Léa aime l'école, mais elle préfère le mercredi parce qu'elle a musique et sport. » Waarom vindt Léa woensdag het leukst?",
    category: "lezen",
    type: "multiple-choice",
    difficulty: 3,
    learningGoal: "Ik leid een eenvoudige reden af uit een tekst.",
    options: ["Ze is dan vrij.", "Ze heeft muziek en sport.", "Ze heeft alleen Frans.", "Ze gaat naar huis."],
    answer: "Ze heeft muziek en sport.",
    hint: "Kijk naar het deel na parce que.",
    explanation: "Parce qu'elle a musique et sport geeft de reden.",
  },

  {
    id: "listen-1",
    title: "Naam en leeftijd",
    instruction: "Luister en kies de juiste samenvatting.",
    category: "luisteren",
    type: "listening",
    difficulty: 1,
    learningGoal: "Ik begrijp naam en leeftijd in een korte boodschap.",
    audioText: "Bonjour, je m'appelle Louis et j'ai douze ans.",
    audioSpeaker: { name: "Louis", gender: "male" },
    options: ["Hij heet Louis en is twaalf jaar.", "Hij heet Lucas en is elf jaar.", "Hij heet Louis en is tien jaar.", "Hij heet Hugo en is twaalf jaar."],
    answer: "Hij heet Louis en is twaalf jaar.",
    hint: "Luister afzonderlijk naar de naam en naar het getal.",
    explanation: "Louis zegt dat hij twaalf jaar is.",
  },
  {
    id: "listen-2",
    title: "Lievelingsvak",
    instruction: "Luister. Welk vak vindt Léa het leukst?",
    category: "luisteren",
    type: "listening",
    difficulty: 2,
    learningGoal: "Ik onderscheid een voorkeur van andere informatie.",
    audioText: "Bonjour, je m'appelle Léa. J'aime le français, mais ma matière préférée est la musique.",
    audioSpeaker: { name: "Léa", gender: "female" },
    options: ["Frans", "muziek", "wiskunde", "sport"],
    answer: "muziek",
    hint: "Let op de woorden ma matière préférée.",
    explanation: "Ma matière préférée est la musique betekent dat muziek haar lievelingsvak is.",
  },
  {
    id: "listen-3",
    title: "Tijdstip",
    instruction: "Luister. Hoe laat begint de les?",
    category: "luisteren",
    type: "listening",
    difficulty: 2,
    learningGoal: "Ik begrijp een eenvoudig tijdstip.",
    audioText: "Le cours commence à huit heures et demie.",
    audioSpeaker: { name: "Madame Martin", gender: "female" },
    options: ["8.00 uur", "8.15 uur", "8.30 uur", "9.30 uur"],
    answer: "8.30 uur",
    hint: "Et demie betekent een halfuur erbij.",
    explanation: "Huit heures et demie is half negen: 8.30 uur.",
  },
  {
    id: "listen-4",
    title: "Twee details combineren",
    instruction: "Luister. Waar en wanneer spreken ze af?",
    category: "luisteren",
    type: "listening",
    difficulty: 3,
    learningGoal: "Ik combineer twee gegevens uit een korte boodschap.",
    audioText: "On se retrouve samedi à quatorze heures devant la bibliothèque.",
    audioSpeaker: { name: "Lucas", gender: "male" },
    options: ["zaterdag om 14 uur aan de bibliotheek", "zondag om 14 uur aan de school", "zaterdag om 4 uur aan de bibliotheek", "vrijdag om 14 uur aan het station"],
    answer: "zaterdag om 14 uur aan de bibliotheek",
    hint: "Luister naar de dag, het uur en de plaats.",
    explanation: "Samedi, à quatorze heures, devant la bibliothèque geeft alle drie de gegevens.",
  },

  {
    id: "write-1",
    title: "Jezelf voorstellen",
    instruction: "Schrijf minstens vijf Franse zinnen. Vermeld je naam, leeftijd, woonplaats, gezin en hobby.",
    category: "schrijven",
    type: "open",
    difficulty: 1,
    learningGoal: "Ik schrijf een korte, begrijpelijke voorstelling.",
    minimumWords: 20,
    example: "Je m'appelle Noor. J'ai onze ans. J'habite à Peer. J'ai un frère. J'aime danser.",
    hint: "Gebruik vijf korte zinnen met telkens één gegeven.",
  },
  {
    id: "write-2",
    title: "Mijn schooltas",
    instruction: "Schrijf minstens vier zinnen over wat er in je schooltas zit. Gebruik il y a en minstens vier schoolwoorden.",
    category: "schrijven",
    type: "open",
    difficulty: 2,
    learningGoal: "Ik beschrijf eenvoudige voorwerpen in volledige zinnen.",
    minimumWords: 22,
    example: "Dans mon sac, il y a deux livres. Il y a une trousse, un cahier et une règle.",
    hint: "Begin met Dans mon sac, il y a ... en voeg daarna details toe.",
  },
  {
    id: "write-3",
    title: "Een kort bericht",
    instruction: "Schrijf een bericht van minstens 30 woorden aan een Franse klasgenoot. Stel jezelf voor en stel twee eenvoudige vragen.",
    category: "schrijven",
    type: "open",
    difficulty: 3,
    learningGoal: "Ik schrijf een samenhangend kort bericht met vragen.",
    minimumWords: 30,
    example: "Bonjour! Je m'appelle Sara et j'ai onze ans. J'habite en Belgique. J'aime la musique. Comment tu t'appelles? Quel âge as-tu? À bientôt!",
    hint: "Gebruik een begroeting, drie zinnen over jezelf, twee vragen en een afsluiting.",
  },

  {
    id: "speak-1",
    title: "Korte kennismaking",
    instruction: "Bereid een voorstelling van ongeveer 30 seconden voor. Vertel je naam, leeftijd, woonplaats en hobby.",
    category: "spreken",
    type: "open",
    difficulty: 1,
    learningGoal: "Ik stel mezelf begrijpelijk voor.",
    minimumWords: 14,
    example: "Bonjour! Je m'appelle Lina. J'ai onze ans. J'habite à Peer. J'aime le football et la musique.",
    hint: "Werk met vier vaste zinsstarters: Je m'appelle, J'ai, J'habite en J'aime.",
  },
  {
    id: "speak-2",
    title: "Hulp vragen in de klas",
    instruction: "Formuleer een beleefde vraag wanneer je een opdracht niet begrijpt.",
    category: "spreken",
    type: "open",
    difficulty: 2,
    learningGoal: "Ik vraag op een beleefde manier om herhaling of uitleg.",
    minimumWords: 6,
    example: "Pardon, madame. Vous pouvez répéter, s'il vous plaît?",
    hint: "Begin met Pardon en eindig met s'il vous plaît.",
  },
  {
    id: "speak-3",
    title: "Een keuze toelichten",
    instruction: "Vertel welk schoolvak je graag doet en geef één reden. Spreek ongeveer 30 seconden.",
    category: "spreken",
    type: "open",
    difficulty: 3,
    learningGoal: "Ik geef een eenvoudige mening met een reden.",
    minimumWords: 15,
    example: "Ma matière préférée est la musique parce que j'aime chanter et jouer du piano.",
    hint: "Gebruik Ma matière préférée est ... parce que ...",
  },

  {
    id: "culture-1",
    title: "Frankrijk",
    instruction: "Wat is de hoofdstad van Frankrijk?",
    category: "cultuur",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik herken enkele basisgegevens over de Franstalige wereld.",
    options: ["Lyon", "Marseille", "Paris", "Lille"],
    answer: "Paris",
    hint: "De stad ligt aan de Seine.",
    explanation: "Paris is de hoofdstad van Frankrijk.",
  },
  {
    id: "culture-2",
    title: "Franstalig België",
    instruction: "In welk Belgisch gewest is Frans de belangrijkste bestuurstaal?",
    category: "cultuur",
    type: "multiple-choice",
    difficulty: 1,
    learningGoal: "Ik herken de belangrijkste Franstalige regio van België.",
    options: ["Vlaanderen", "Wallonië", "de Noordzee", "de Kempen"],
    answer: "Wallonië",
    hint: "Denk aan het zuidelijke gewest van België.",
    explanation: "In Wallonië is Frans de belangrijkste bestuurstaal.",
  },
  {
    id: "culture-3",
    title: "Meer dan Frankrijk",
    instruction: "In welk van deze landen is Frans ook een officiële taal?",
    category: "cultuur",
    type: "multiple-choice",
    difficulty: 2,
    learningGoal: "Ik besef dat Frans in meerdere landen wordt gebruikt.",
    options: ["Zwitserland", "Portugal", "Zweden", "Polen"],
    answer: "Zwitserland",
    hint: "Het land heeft meerdere officiële talen.",
    explanation: "Frans is een van de officiële talen van Zwitserland.",
  },
  {
    id: "culture-4",
    title: "Formeel en informeel",
    instruction: "Welke aanspreekvorm gebruik je meestal tegen een onbekende volwassene?",
    category: "cultuur",
    type: "multiple-choice",
    difficulty: 2,
    learningGoal: "Ik herken een eenvoudige beleefdheidsconventie.",
    options: ["tu", "vous", "ils", "nous"],
    answer: "vous",
    hint: "Kies de beleefde vorm.",
    explanation: "Vous gebruik je in formele situaties of tegen een onbekende volwassene.",
  },
];

export const frenchPreparationSections: FrenchPreparationSection[] = [
  { id: "woordenschat", title: "Woordenschat", description: "Basiswoorden die je nodig hebt om jezelf te redden.", icon: "blocks" },
  { id: "grammatica", title: "Grammatica", description: "Zinsbouw en werkwoorden die vaak terugkomen.", icon: "book" },
  { id: "lezen", title: "Lezen", description: "Korte berichten, teksten en praktische informatie.", icon: "book" },
  { id: "luisteren", title: "Luisteren", description: "Belangrijke informatie uit korte boodschappen halen.", icon: "headphones" },
  { id: "schrijven", title: "Schrijven", description: "Korte en begrijpelijke Franse teksten maken.", icon: "pen" },
  { id: "spreken", title: "Spreken", description: "Jezelf voorstellen en eenvoudige vragen stellen.", icon: "mic" },
  { id: "cultuur", title: "Franstalige wereld", description: "Taal, regio’s en beleefdheid leren kennen.", icon: "globe" },
];
