import { mc, type ExerciseInput, type Random } from "./shared";

type Question = readonly [string, readonly string[], string];

const levels: readonly (readonly Question[])[] = [
  [
    ["Wat is de persoonsvorm in: ‘Mila leest elke avond een boek.’?", ["leest", "Mila", "boek", "elke avond"], "leest"],
    ["Wat is het onderwerp in: ‘De hond blaft naar de postbode.’?", ["de hond", "blaft", "de postbode", "naar"], "de hond"],
    ["Welke zin staat in de tegenwoordige tijd?", ["Noor fietst naar school.", "Noor fietste naar school.", "Noor heeft gefietst.", "Noor zal fietsen."], "Noor fietst naar school."],
    ["Welke zin staat in de verleden tijd?", ["Wij speelden buiten.", "Wij spelen buiten.", "Wij zullen spelen.", "Wij hebben gespeeld."], "Wij speelden buiten."],
    ["Welk woord is een zelfstandig naamwoord?", ["tafel", "lopen", "mooi", "onder"], "tafel"],
    ["Welk woord is een werkwoord?", ["springen", "sprong", "hoog", "de"], "springen"],
    ["Welk woord is een lidwoord?", ["het", "klein", "huis", "staat"], "het"],
    ["Welk woord is een bijvoeglijk naamwoord in: ‘De rode fiets staat buiten.’?", ["rode", "fiets", "staat", "buiten"], "rode"],
    ["Welke woorden vormen het onderwerp in: ‘Mijn beste vriend woont dichtbij.’?", ["mijn beste vriend", "woont", "dichtbij", "beste"], "mijn beste vriend"],
    ["Maak de zin vragend. Welke vorm is correct?", ["Komt Lina morgen?", "Lina komt morgen?", "Morgen Lina komt?", "Komt morgen Lina."], "Komt Lina morgen?"],
    ["Welke zin is een mededelende zin?", ["De les begint om negen uur.", "Begint de les om negen uur?", "Kom op tijd!", "Wat een leuke les!"], "De les begint om negen uur."],
    ["Welke zin is een vraagzin?", ["Waar ligt mijn schrift?", "Mijn schrift ligt hier.", "Pak je schrift.", "Wat een mooi schrift!"], "Waar ligt mijn schrift?"],
    ["Wat is de infinitief van ‘loopt’?", ["lopen", "liep", "gelopen", "loop"], "lopen"],
    ["Wat is de stam van ‘werken’?", ["werk", "werken", "werkte", "gewerkt"], "werk"],
    ["Welk woord is een eigennaam?", ["Brussel", "stad", "straat", "school"], "Brussel"],
    ["Welk woord is een voornaamwoord in: ‘Zij leest het boek.’?", ["zij", "leest", "boek", "het"], "zij"],
    ["Welke zin heeft onderwerp en persoonsvorm in de juiste volgorde?", ["De leerlingen luisteren aandachtig.", "Luisteren de leerlingen aandachtig.", "Aandachtig de leerlingen luisteren.", "De leerlingen aandachtig."], "De leerlingen luisteren aandachtig."],
    ["Welke woordgroep vertelt wie iets doet?", ["het onderwerp", "de persoonsvorm", "het lidwoord", "het bijvoeglijk naamwoord"], "het onderwerp"],
  ],
  [
    ["Wat is de persoonsvorm in: ‘Gisteren maakten de leerlingen een toets.’?", ["maakten", "gisteren", "de leerlingen", "een toets"], "maakten"],
    ["Wat is het onderwerp in: ‘Op het plein spelen drie kinderen.’?", ["drie kinderen", "op het plein", "spelen", "plein"], "drie kinderen"],
    ["Welke proef helpt om de persoonsvorm te vinden?", ["de zin van tijd veranderen", "het langste woord zoeken", "alle zelfstandige naamwoorden schrappen", "de zin alfabetisch zetten"], "de zin van tijd veranderen"],
    ["Welke zin heeft een enkelvoudig onderwerp?", ["De kat slaapt.", "De kat en de hond slapen.", "Mijn ouders koken.", "De kinderen spelen."], "De kat slaapt."],
    ["Welke zin heeft een meervoudig onderwerp?", ["De spelers trainen.", "De speler traint.", "Het team traint.", "Mijn broer traint."], "De spelers trainen."],
    ["Welk woord is een voorzetsel?", ["onder", "lopen", "zacht", "fiets"], "onder"],
    ["Welk woord is een telwoord?", ["zeven", "groot", "daar", "omdat"], "zeven"],
    ["Welk woord is een persoonlijk voornaamwoord?", ["wij", "onze", "welke", "deze"], "wij"],
    ["Welk woord is een bezittelijk voornaamwoord?", ["mijn", "ik", "mij", "wie"], "mijn"],
    ["Welk woord is een bijwoord in: ‘Hij loopt snel naar huis.’?", ["snel", "loopt", "huis", "naar"], "snel"],
    ["Welke zin staat in de voltooide tijd?", ["Zij heeft haar taak gemaakt.", "Zij maakt haar taak.", "Zij maakte haar taak.", "Zij zal haar taak maken."], "Zij heeft haar taak gemaakt."],
    ["Wat is het voltooid deelwoord in: ‘Wij hebben lang gewacht.’?", ["gewacht", "hebben", "wij", "lang"], "gewacht"],
    ["Welke zin bevat een hulpwerkwoord?", ["Hij heeft gewonnen.", "Hij wint.", "Hij loopt.", "Hij lacht."], "Hij heeft gewonnen."],
    ["Wat is de infinitief in: ‘Wij willen morgen vertrekken.’?", ["vertrekken", "willen", "morgen", "wij"], "vertrekken"],
    ["Welke zin is gebiedend?", ["Sluit de deur.", "Sluit je de deur?", "De deur is gesloten.", "Hij sluit de deur."], "Sluit de deur."],
    ["Welke zin is uitroepend?", ["Wat een prachtige dag!", "Is het een prachtige dag?", "Het is een prachtige dag.", "Maak er een prachtige dag van."], "Wat een prachtige dag!"],
    ["Wat gebeurt er met de persoonsvorm wanneer je de zin van tijd verandert?", ["de vorm verandert", "het woord verdwijnt", "de plaats verandert altijd", "er verandert niets"], "de vorm verandert"],
    ["Welke woordsoort benoemt een eigenschap van een zelfstandig naamwoord?", ["bijvoeglijk naamwoord", "werkwoord", "voorzetsel", "lidwoord"], "bijvoeglijk naamwoord"],
  ],
  [
    ["Wat is het lijdend voorwerp in: ‘De leerling leest het hoofdstuk.’?", ["het hoofdstuk", "de leerling", "leest", "geen"], "het hoofdstuk"],
    ["Welke vraag gebruik je om het lijdend voorwerp te vinden?", ["Wie of wat + gezegde + onderwerp?", "Waar + persoonsvorm?", "Wanneer + onderwerp?", "Hoeveel woorden telt de zin?"], "Wie of wat + gezegde + onderwerp?"],
    ["Wat is het lijdend voorwerp in: ‘Sara koopt een nieuwe jas.’?", ["een nieuwe jas", "Sara", "koopt", "nieuwe"], "een nieuwe jas"],
    ["Welke zin heeft géén lijdend voorwerp?", ["De baby slaapt.", "De kok snijdt de groenten.", "Milan opent het raam.", "Wij bekijken de film."], "De baby slaapt."],
    ["Welk woord is een aanwijzend voornaamwoord?", ["deze", "ik", "mijn", "wie"], "deze"],
    ["Welk woord is een vragend voornaamwoord?", ["wie", "zij", "hun", "dit"], "wie"],
    ["Welk woord is een voegwoord?", ["maar", "naast", "snel", "boek"], "maar"],
    ["Welk woord verbindt twee zinnen in: ‘Ik blijf binnen omdat het regent.’?", ["omdat", "binnen", "regent", "ik"], "omdat"],
    ["Welk woord is een bijwoord in: ‘Morgen vertrekken we vroeg.’?", ["morgen", "vertrekken", "we", "vroeg"], "morgen"],
    ["Welk woord is een bijvoeglijk naamwoord in: ‘Het moeilijke examen duurde lang.’?", ["moeilijke", "examen", "duurde", "lang"], "moeilijke"],
    ["Welke zin bevat een scheidbaar werkwoord?", ["Zij ruimt haar kamer op.", "Zij poetst haar kamer.", "Zij verlaat haar kamer.", "Zij bekijkt haar kamer."], "Zij ruimt haar kamer op."],
    ["Wat is het hele werkwoord in: ‘Hij staat elke ochtend vroeg op.’?", ["opstaan", "staan", "vroeg op", "staat"], "opstaan"],
    ["Welke zin bevat een wederkerend voornaamwoord?", ["Hij vergist zich.", "Hij ziet hem.", "Hij helpt haar.", "Hij kent ons."], "Hij vergist zich."],
    ["Wat is het wederkerend voornaamwoord in: ‘Wij haasten ons.’?", ["ons", "wij", "haasten", "geen"], "ons"],
    ["Welke zin bevat een telwoord?", ["Drie leerlingen ontbreken.", "Enkele leerlingen ontbreken.", "De leerlingen ontbreken.", "Leerlingen ontbreken vaak."], "Drie leerlingen ontbreken."],
    ["Welk woord is een onbepaald telwoord?", ["veel", "acht", "achtste", "dubbel"], "veel"],
    ["Welk zinsdeel antwoordt op ‘wie of wat wordt gelezen?’ in ‘Noor leest de krant’?", ["de krant", "Noor", "leest", "geen"], "de krant"],
    ["Welke zin bevat twee werkwoordsvormen?", ["Wij zullen morgen vertrekken.", "Wij vertrekken morgen.", "Morgen vertrek.", "Vertrek morgen!"], "Wij zullen morgen vertrekken."],
  ],
  [
    ["Wat is het meewerkend voorwerp in: ‘De leraar geeft de leerling een boek.’?", ["de leerling", "een boek", "de leraar", "geeft"], "de leerling"],
    ["Welke vraag helpt om het meewerkend voorwerp te vinden?", ["Aan wie of voor wie?", "Wie of wat doet iets?", "Waar gebeurt het?", "Wanneer gebeurt het?"], "Aan wie of voor wie?"],
    ["Wat is het meewerkend voorwerp in: ‘Mijn zus stuurt mij een bericht.’?", ["mij", "een bericht", "mijn zus", "stuurt"], "mij"],
    ["Welke zin bevat een meewerkend voorwerp?", ["Opa vertelt ons een verhaal.", "Opa leest een verhaal.", "Opa slaapt.", "Opa wandelt buiten."], "Opa vertelt ons een verhaal."],
    ["Wat is het lijdend voorwerp in: ‘Opa vertelt ons een verhaal.’?", ["een verhaal", "ons", "opa", "vertelt"], "een verhaal"],
    ["Wat is het werkwoordelijk gezegde in: ‘De leerlingen hebben hard gewerkt.’?", ["hebben gewerkt", "hard gewerkt", "de leerlingen", "gewerkt"], "hebben gewerkt"],
    ["Welke woorden horen bij het werkwoordelijk gezegde in: ‘Zij zal morgen vertrekken.’?", ["zal vertrekken", "morgen vertrekken", "zij zal", "vertrekken"], "zal vertrekken"],
    ["Welke zin bevat een werkwoordelijk gezegde?", ["De leerling maakt de oefening.", "De leerling is moe.", "De leerling lijkt ziek.", "De leerling wordt boos."], "De leerling maakt de oefening."],
    ["Welk woord is een betrekkelijk voornaamwoord?", ["die", "zij", "mijn", "welke"], "die"],
    ["Welk woord verwijst terug naar ‘de jongen’ in: ‘De jongen die daar loopt’?", ["die", "daar", "loopt", "de"], "die"],
    ["Welke zin bevat een voorzetselvoorwerp?", ["Zij wacht op de bus.", "Zij wacht buiten.", "Zij neemt de bus.", "Zij mist de bus."], "Zij wacht op de bus."],
    ["Wat is het voorzetselvoorwerp in: ‘Hij verlangt naar vakantie.’?", ["naar vakantie", "hij", "verlangt", "vakantie"], "naar vakantie"],
    ["Welke woordgroep is een bijwoordelijke bepaling van tijd?", ["na de les", "in de tuin", "met plezier", "door de storm"], "na de les"],
    ["Welke woordgroep is een bijwoordelijke bepaling van plaats?", ["op het plein", "gisteren", "met aandacht", "door de regen"], "op het plein"],
    ["Wat is de bijwoordelijke bepaling in: ‘Morgen oefenen we in de bibliotheek.’?", ["morgen en in de bibliotheek", "we", "oefenen", "de bibliotheek"], "morgen en in de bibliotheek"],
    ["Welke zin bevat een bijwoordelijke bepaling van wijze?", ["Hij antwoordt rustig.", "Hij antwoordt morgen.", "Hij antwoordt in de klas.", "Hij antwoordt de leraar."], "Hij antwoordt rustig."],
    ["Welke zin bevat zowel een lijdend als een meewerkend voorwerp?", ["De coach geeft de spelers advies.", "De coach praat.", "De coach wacht buiten.", "De coach wordt boos."], "De coach geeft de spelers advies."],
    ["Welke woordgroep is het onderwerp in: ‘Aan de winnaar werd een medaille gegeven.’?", ["een medaille", "aan de winnaar", "werd gegeven", "de winnaar"], "een medaille"],
  ],
  [
    ["Welke zin bevat een naamwoordelijk gezegde?", ["De opdracht is moeilijk.", "De leerling maakt de opdracht.", "Wij lezen de tekst.", "Zij opent het boek."], "De opdracht is moeilijk."],
    ["Wat is het naamwoordelijk gezegde in: ‘Mijn broer wordt dokter.’?", ["wordt dokter", "mijn broer", "wordt", "dokter"], "wordt dokter"],
    ["Wat is het naamwoordelijk deel in: ‘De lucht blijft grijs.’?", ["grijs", "blijft", "de lucht", "blijft grijs"], "grijs"],
    ["Welk werkwoord kan een koppelwerkwoord zijn?", ["blijven", "lopen", "schrijven", "kopen"], "blijven"],
    ["Welke zin bevat een koppelwerkwoord?", ["Het eten smaakt heerlijk.", "De kok proeft het eten.", "De kok maakt soep.", "Het eten kookt."], "Het eten smaakt heerlijk."],
    ["Welke zin bevat een werkwoordelijk gezegde?", ["De hond rent snel.", "De hond is moe.", "De hond blijft rustig.", "De hond lijkt bang."], "De hond rent snel."],
    ["Wat is het gezegde in: ‘De voorstelling is erg spannend.’?", ["is erg spannend", "de voorstelling", "erg", "spannend"], "is erg spannend"],
    ["Wat is het onderwerp in: ‘Er staan drie fietsen voor de school.’?", ["drie fietsen", "er", "voor de school", "staan"], "drie fietsen"],
    ["Welke zin bevat een voorlopig onderwerp?", ["Het is duidelijk dat hij gelijk heeft.", "Het boek is duidelijk.", "Hij heeft gelijk.", "Dat antwoord is duidelijk."], "Het is duidelijk dat hij gelijk heeft."],
    ["Welke zin bevat een onpersoonlijk onderwerp?", ["Het regent hard.", "Het kind speelt.", "De regen valt.", "Die wolk verdwijnt."], "Het regent hard."],
    ["Wat is de bijvoeglijke bepaling in: ‘De tas van mijn zus is zwaar.’?", ["van mijn zus", "de tas", "is zwaar", "zwaar"], "van mijn zus"],
    ["Welke woordgroep is een bijvoeglijke bepaling?", ["met de rode kaft", "gisteren", "heel snel", "door de wind"], "met de rode kaft"],
    ["Welke zin bevat een bepaling van gesteldheid?", ["Hij kwam vermoeid thuis.", "Hij kwam gisteren thuis.", "Hij kwam met de bus thuis.", "Hij kwam thuis."], "Hij kwam vermoeid thuis."],
    ["Wat is de bepaling van gesteldheid in: ‘Ze schilderde de muur blauw.’?", ["blauw", "de muur", "schilderde", "ze"], "blauw"],
    ["Welke zin is actief?", ["De leerling schrijft het verslag.", "Het verslag wordt geschreven.", "Het verslag is geschreven.", "Er wordt geschreven."], "De leerling schrijft het verslag."],
    ["Welke zin is passief?", ["Het verslag wordt door de leerling geschreven.", "De leerling schrijft het verslag.", "De leerling heeft geschreven.", "De leerling wil schrijven."], "Het verslag wordt door de leerling geschreven."],
    ["Wat is het handelend voorwerp in: ‘De brief wordt door Sara verstuurd.’?", ["door Sara", "de brief", "wordt verstuurd", "verstuurd"], "door Sara"],
    ["Welke combinatie vormt een naamwoordelijk gezegde?", ["koppelwerkwoord + naamwoordelijk deel", "hulpwerkwoord + infinitief", "onderwerp + lijdend voorwerp", "voorzetsel + zelfstandig naamwoord"], "koppelwerkwoord + naamwoordelijk deel"],
  ],
  [
    ["Welke zin bevat een hoofdzin en een bijzin?", ["Ik blijf thuis omdat ik ziek ben.", "Ik blijf vandaag thuis.", "Blijf vandaag thuis!", "Ben je vandaag thuis?"], "Ik blijf thuis omdat ik ziek ben."],
    ["Wat is de bijzin in: ‘Omdat het regent, nemen we de bus.’?", ["Omdat het regent", "nemen we de bus", "we", "de bus"], "Omdat het regent"],
    ["Wat is de hoofdzin in: ‘Omdat het regent, nemen we de bus.’?", ["nemen we de bus", "omdat het regent", "het regent", "de bus"], "nemen we de bus"],
    ["Welk woord leidt de bijzin in: ‘Ik weet dat hij komt’ in?", ["dat", "weet", "hij", "komt"], "dat"],
    ["Welke zin bevat een betrekkelijke bijzin?", ["Het boek dat ik lees is spannend.", "Ik lees omdat het stil is.", "Ik weet dat hij leest.", "Als hij leest, is het stil."], "Het boek dat ik lees is spannend."],
    ["Wat is de betrekkelijke bijzin in: ‘De jas die ik kocht is blauw.’?", ["die ik kocht", "de jas", "is blauw", "ik kocht"], "die ik kocht"],
    ["Welk woord is een onderschikkend voegwoord?", ["omdat", "en", "maar", "of"], "omdat"],
    ["Welk woord is een nevenschikkend voegwoord?", ["maar", "terwijl", "doordat", "hoewel"], "maar"],
    ["Welke zin bevat nevenschikking?", ["Hij leert en zij oefent.", "Hij leert omdat hij morgen toets heeft.", "Hoewel hij moe is, leert hij.", "Als hij klaar is, rust hij."], "Hij leert en zij oefent."],
    ["Welke zin bevat onderschikking?", ["Wij gaan naar binnen omdat het koud is.", "Wij gaan naar binnen en drinken thee.", "Wij gaan naar binnen, maar zij blijft buiten.", "Kom binnen of blijf buiten."], "Wij gaan naar binnen omdat het koud is."],
    ["Waar staat de persoonsvorm meestal in een bijzin?", ["achteraan", "altijd vooraan", "op de tweede plaats", "nooit in de zin"], "achteraan"],
    ["Welke woordvolgorde hoort bij een bijzin?", ["omdat hij morgen komt", "omdat komt hij morgen", "hij komt omdat morgen", "komt omdat hij morgen"], "omdat hij morgen komt"],
    ["Welke zin bevat een redengevende bijzin?", ["Ik blijf thuis omdat ik ziek ben.", "Ik blijf thuis als het regent.", "Ik blijf thuis hoewel ik beter ben.", "Ik blijf thuis voordat het donker wordt."], "Ik blijf thuis omdat ik ziek ben."],
    ["Welke zin bevat een voorwaardelijke bijzin?", ["Als je oefent, word je beter.", "Omdat je oefent, word je beter.", "Hoewel je oefent, word je beter.", "Nadat je oefent, word je beter."], "Als je oefent, word je beter."],
    ["Welke zin bevat een toegevende bijzin?", ["Hoewel hij moe is, werkt hij door.", "Omdat hij moe is, stopt hij.", "Als hij moe is, rust hij.", "Voordat hij moe is, stopt hij."], "Hoewel hij moe is, werkt hij door."],
    ["Welke zin bevat een tijdsbijzin?", ["Nadat de les eindigde, ging iedereen weg.", "Omdat de les eindigde, ging iedereen weg.", "Hoewel de les eindigde, bleef hij.", "Als de les moeilijk is, vraagt hij hulp."], "Nadat de les eindigde, ging iedereen weg."],
    ["Wat is het antecedent van ‘die’ in: ‘De leerling die wint krijgt een prijs.’?", ["de leerling", "wint", "een prijs", "krijgt"], "de leerling"],
    ["Welke zin bevat een beknopte bijzin?", ["Om te slagen, moet je oefenen.", "Omdat je wilt slagen, moet je oefenen.", "Je oefent en je slaagt.", "Je moet oefenen."], "Om te slagen, moet je oefenen."],
  ],
  [
    ["Wat is de bijwoordelijke bepaling van tijd in: ‘Morgen vertrekken we vroeg.’?", ["morgen", "vroeg", "we", "vertrekken"], "morgen"],
    ["Wat is de bijwoordelijke bepaling van plaats in: ‘De kinderen spelen op het plein.’?", ["op het plein", "de kinderen", "spelen", "het plein"], "op het plein"],
    ["Wat is de bijwoordelijke bepaling van wijze in: ‘Zij antwoordde heel rustig.’?", ["heel rustig", "zij", "antwoordde", "rustig"], "heel rustig"],
    ["Welke zin bevat een bijwoordelijke bepaling van oorzaak?", ["Door de storm viel de stroom uit.", "Tijdens de storm bleef hij binnen.", "Na de storm ging hij buiten.", "Bij de storm hoorde hij donder."], "Door de storm viel de stroom uit."],
    ["Welke zin bevat een bijwoordelijke bepaling van doel?", ["Hij oefent om te slagen.", "Hij oefent omdat hij bang is.", "Hij oefent na school.", "Hij oefent in zijn kamer."], "Hij oefent om te slagen."],
    ["Welke zin bevat een bijwoordelijke bepaling van middel?", ["Ze opent de doos met een schaar.", "Ze opent de doos morgen.", "Ze opent de doos voorzichtig.", "Ze opent de doos in de keuken."], "Ze opent de doos met een schaar."],
    ["Welke zin bevat een bijwoordelijke bepaling van reden?", ["Uit angst zweeg hij.", "Met een sleutel opende hij de deur.", "In de klas zweeg hij.", "Gisteren zweeg hij."], "Uit angst zweeg hij."],
    ["Wat is het voorzetselvoorwerp in: ‘Wij rekenen op jouw hulp.’?", ["op jouw hulp", "wij", "rekenen", "jouw hulp"], "op jouw hulp"],
    ["Welke zin heeft géén voorzetselvoorwerp maar een plaatsbepaling?", ["Hij wacht op het perron.", "Hij rekent op steun.", "Hij verlangt naar rust.", "Hij twijfelt aan het antwoord."], "Hij wacht op het perron."],
    ["Welke zin bevat een bepaling van gesteldheid?", ["De spelers keerden teleurgesteld terug.", "De spelers keerden gisteren terug.", "De spelers keerden naar huis terug.", "De spelers keerden met de bus terug."], "De spelers keerden teleurgesteld terug."],
    ["Wat is het naamwoordelijk deel in: ‘De oplossing lijkt eenvoudig.’?", ["eenvoudig", "lijkt", "de oplossing", "lijkt eenvoudig"], "eenvoudig"],
    ["Welke zin bevat een naamwoordelijk gezegde?", ["De resultaten blijven onzeker.", "De onderzoekers bespreken de resultaten.", "De resultaten veranderen snel.", "De onderzoekers publiceren."], "De resultaten blijven onzeker."],
    ["Welke zin bevat een handelend voorwerp?", ["De tekst werd door de redactie aangepast.", "De redactie paste de tekst aan.", "De tekst is duidelijk.", "De tekst verscheen gisteren."], "De tekst werd door de redactie aangepast."],
    ["Zet actief om naar passief. Welke zin is correct? ‘De jury beoordeelt de inzendingen.’", ["De inzendingen worden door de jury beoordeeld.", "De jury wordt door de inzendingen beoordeeld.", "De inzendingen beoordelen de jury.", "Er beoordeelt de jury de inzendingen."], "De inzendingen worden door de jury beoordeeld."],
    ["Zet passief om naar actief. Welke zin is correct? ‘De winnaar werd door de jury gekozen.’", ["De jury koos de winnaar.", "De winnaar koos de jury.", "De jury werd gekozen.", "De winnaar heeft gekozen."], "De jury koos de winnaar."],
    ["Welke woordgroep is een bijvoeglijke bepaling?", ["de leerling met de blauwe jas", "de leerling loopt snel", "de leerling komt morgen", "de leerling staat buiten"], "de leerling met de blauwe jas"],
    ["Welke bijzin is een lijdend-voorwerpszin?", ["Ik weet dat hij komt.", "Wie hard werkt, slaagt.", "Omdat hij komt, wacht ik.", "De jongen die komt, lacht."], "Ik weet dat hij komt."],
    ["Welke bijzin is een onderwerpszin?", ["Dat zij wint, verbaast niemand.", "Ik hoop dat zij wint.", "Omdat zij wint, juicht ze.", "De prijs die zij wint is groot."], "Dat zij wint, verbaast niemand."],
  ],
  [
    ["Wat is het meewerkend voorwerp in: ‘De docent legde de studenten de theorie uit.’?", ["de studenten", "de theorie", "de docent", "legde uit"], "de studenten"],
    ["Wat is het lijdend voorwerp in dezelfde zin?", ["de theorie", "de studenten", "de docent", "uit"], "de theorie"],
    ["Wat is het werkwoordelijk gezegde in: ‘De commissie zal het voorstel opnieuw moeten beoordelen.’?", ["zal moeten beoordelen", "opnieuw beoordelen", "het voorstel", "de commissie"], "zal moeten beoordelen"],
    ["Welke zin bevat een naamwoordelijk gezegde?", ["De maatregel bleek onvoldoende effectief.", "De commissie onderzocht de maatregel.", "De maatregel veranderde de situatie.", "De commissie publiceerde."], "De maatregel bleek onvoldoende effectief."],
    ["Wat is het naamwoordelijk deel in: ‘Haar verklaring klinkt overtuigend.’?", ["overtuigend", "klinkt", "haar verklaring", "klinkt overtuigend"], "overtuigend"],
    ["Welke bijzin is een betrekkelijke bijzin?", ["De resultaten die gisteren verschenen zijn opvallend.", "Omdat de resultaten verschenen, reageerde men.", "Ik weet dat de resultaten verschenen.", "Als de resultaten verschijnen, bellen we."], "De resultaten die gisteren verschenen zijn opvallend."],
    ["Welke bijzin is een bijwoordelijke bijzin van tegenstelling?", ["Hoewel de cijfers stijgen, blijft de winst laag.", "Omdat de cijfers stijgen, groeit de winst.", "Als de cijfers stijgen, groeit de winst.", "Nadat de cijfers stijgen, groeit de winst."], "Hoewel de cijfers stijgen, blijft de winst laag."],
    ["Welke zin bevat een beknopte bijzin met ‘om te’?", ["Om de fout te herstellen, paste hij de tekst aan.", "Omdat hij de fout herstelde, paste hij de tekst aan.", "Hij herstelde de fout en paste de tekst aan.", "Hij paste de tekst aan."], "Om de fout te herstellen, paste hij de tekst aan."],
    ["Wat is het antecedent in: ‘De methode waarop het onderzoek steunt is betrouwbaar.’?", ["de methode", "het onderzoek", "betrouwbaar", "waarop"], "de methode"],
    ["Welke zin bevat een voorzetselvoorwerp?", ["De onderzoeker twijfelt aan de conclusie.", "De onderzoeker werkt aan tafel.", "De onderzoeker schrijft met een pen.", "De onderzoeker vertrekt na de middag."], "De onderzoeker twijfelt aan de conclusie."],
    ["Welke zin bevat een bijwoordelijke bepaling van voorwaarde?", ["Bij voldoende bewijs wordt de hypothese aanvaard.", "Door voldoende bewijs werd ze aanvaard.", "Met voldoende bewijs werd ze ondersteund.", "Na het bewijs werd ze besproken."], "Bij voldoende bewijs wordt de hypothese aanvaard."],
    ["Welke zin bevat een bepaling van gesteldheid?", ["De jury verklaarde hem onschuldig.", "De jury hoorde hem gisteren.", "De jury sprak met hem.", "De jury wachtte buiten."], "De jury verklaarde hem onschuldig."],
    ["Wat is de bepaling van gesteldheid in: ‘Men beschouwde het plan als onhaalbaar.’?", ["als onhaalbaar", "het plan", "men", "beschouwde"], "als onhaalbaar"],
    ["Welke passieve zin heeft een handelend voorwerp?", ["Het rapport werd door drie experts nagelezen.", "Het rapport werd nagelezen.", "Het rapport is volledig.", "Er werd lang vergaderd."], "Het rapport werd door drie experts nagelezen."],
    ["Welke zin is correct omgezet naar actief? ‘De gegevens werden door het team gecontroleerd.’", ["Het team controleerde de gegevens.", "De gegevens controleerden het team.", "Het team werd gecontroleerd.", "Het team had gegevens."], "Het team controleerde de gegevens."],
    ["Welke woordsoort is ‘echter’ in: ‘De resultaten waren echter onzeker.’?", ["bijwoord", "voegwoord", "voorzetsel", "bijvoeglijk naamwoord"], "bijwoord"],
    ["Welke woordsoort is ‘doordat’ in: ‘De proef mislukte doordat de temperatuur daalde.’?", ["onderschikkend voegwoord", "nevenschikkend voegwoord", "voorzetsel", "bijwoord"], "onderschikkend voegwoord"],
    ["Welke zin bevat een lijdend-voorwerpszin?", ["De onderzoekers concludeerden dat de methode werkte.", "Dat de methode werkte, was verrassend.", "De methode die werkte werd gekozen.", "Omdat de methode werkte, werd ze gekozen."], "De onderzoekers concludeerden dat de methode werkte."],
  ],
  [
    ["Welke zin bevat een onderwerpszin?", ["Dat de resultaten afwijken, is opmerkelijk.", "Men merkt dat de resultaten afwijken.", "De resultaten die afwijken zijn opvallend.", "Omdat de resultaten afwijken, volgt onderzoek."], "Dat de resultaten afwijken, is opmerkelijk."],
    ["Welke zin bevat een naamwoordelijk-deelzin?", ["De vraag is of de maatregel werkt.", "Men vraagt of de maatregel werkt.", "Als de maatregel werkt, verandert er veel.", "De maatregel die werkt wordt ingevoerd."], "De vraag is of de maatregel werkt."],
    ["Welke zin bevat een bijvoeglijke bijzin?", ["De gegevens die de onderzoeker verzamelde zijn onvolledig.", "Omdat de gegevens onvolledig zijn, volgt controle.", "Men weet dat de gegevens onvolledig zijn.", "Dat de gegevens onvolledig zijn, verbaast ons."], "De gegevens die de onderzoeker verzamelde zijn onvolledig."],
    ["Welke bijzin geeft een doel aan?", ["opdat iedereen de uitleg begrijpt", "omdat iedereen de uitleg begrijpt", "hoewel iedereen de uitleg begrijpt", "nadat iedereen de uitleg begrijpt"], "opdat iedereen de uitleg begrijpt"],
    ["Welke bijzin geeft een gevolg aan?", ["zodat de meting opnieuw moest gebeuren", "omdat de meting opnieuw gebeurde", "hoewel de meting opnieuw gebeurde", "voordat de meting opnieuw gebeurde"], "zodat de meting opnieuw moest gebeuren"],
    ["Welke bijzin geeft een vergelijking aan?", ["alsof hij alles al wist", "omdat hij alles wist", "nadat hij alles wist", "opdat hij alles wist"], "alsof hij alles al wist"],
    ["Welke zin bevat een beknopte bijzin zonder expliciet onderwerp?", ["Na de gegevens te hebben gecontroleerd, publiceerde de onderzoeker het rapport.", "Nadat de onderzoeker de gegevens controleerde, publiceerde hij het rapport.", "De onderzoeker controleerde en publiceerde.", "De onderzoeker publiceerde het rapport."], "Na de gegevens te hebben gecontroleerd, publiceerde de onderzoeker het rapport."],
    ["Wat is het verzwegen onderwerp van ‘Na de gegevens te hebben gecontroleerd’ in de voorbeeldzin?", ["de onderzoeker", "de gegevens", "het rapport", "niemand"], "de onderzoeker"],
    ["Welke zin bevat foutieve beknopte-bijzinconstructie?", ["Fietsend naar school, begon het te regenen.", "Fietsend naar school, zag Noor donkere wolken.", "Na het boek gelezen te hebben, schreef Amir een verslag.", "Om tijd te besparen, nam Sara de trein."], "Fietsend naar school, begon het te regenen."],
    ["Welke zin bevat een voorzetselvoorwerp?", ["De beslissing hangt af van nieuwe gegevens.", "De beslissing ligt op tafel.", "De beslissing kwam gisteren.", "De beslissing werd snel genomen."], "De beslissing hangt af van nieuwe gegevens."],
    ["Wat is het voorzetselvoorwerp in: ‘De conclusie berust op drie aannames.’?", ["op drie aannames", "de conclusie", "berust", "drie aannames"], "op drie aannames"],
    ["Welke zin bevat een bijwoordelijke bepaling van beperking?", ["Voor zover bekend zijn er geen fouten.", "Door de fout stopte het proces.", "Na de fout volgde controle.", "Met de fout werd rekening gehouden."], "Voor zover bekend zijn er geen fouten."],
    ["Welke zin bevat een bijwoordelijke bepaling van toegeving?", ["Ondanks de kritiek bleef het voorstel behouden.", "Door de kritiek werd het voorstel aangepast.", "Na de kritiek volgde overleg.", "Met kritiek werd rekening gehouden."], "Ondanks de kritiek bleef het voorstel behouden."],
    ["Welke analyse van ‘De bevindingen lijken betrouwbaar’ is correct?", ["naamwoordelijk gezegde: lijken betrouwbaar", "werkwoordelijk gezegde: lijken", "lijdend voorwerp: betrouwbaar", "meewerkend voorwerp: de bevindingen"], "naamwoordelijk gezegde: lijken betrouwbaar"],
    ["Welke analyse van ‘De onderzoekers achten de methode betrouwbaar’ is correct?", ["bepaling van gesteldheid: betrouwbaar", "naamwoordelijk deel: betrouwbaar", "lijdend voorwerp: betrouwbaar", "bijwoordelijke bepaling: betrouwbaar"], "bepaling van gesteldheid: betrouwbaar"],
    ["Welke zin is dubbelzinnig door de plaats van een bepaling?", ["Ik zag de man met de verrekijker.", "Met de verrekijker zag ik de man.", "Ik zag gisteren de man.", "De man stond bij het raam."], "Ik zag de man met de verrekijker."],
    ["Welke woordgroep fungeert als bijvoeglijke bepaling in ‘het onderzoek naar leesgedrag’?", ["naar leesgedrag", "het onderzoek", "leesgedrag", "naar"], "naar leesgedrag"],
    ["Welke zin bevat zowel onderschikking als nevenschikking?", ["Omdat het regende, bleven we binnen en maakten we de opdracht af.", "Het regende en we bleven binnen.", "Omdat het regende, bleven we binnen.", "We bleven binnen maar gingen later weg."], "Omdat het regende, bleven we binnen en maakten we de opdracht af."],
  ],
  [
    ["Welke volledige ontleding is correct voor ‘De docent gaf de leerling gisteren extra uitleg.’?", ["onderwerp: de docent; gezegde: gaf; meewerkend voorwerp: de leerling; lijdend voorwerp: extra uitleg; bijwoordelijke bepaling: gisteren", "onderwerp: de leerling; gezegde: gaf uitleg; lijdend voorwerp: de docent", "onderwerp: extra uitleg; gezegde: gaf; meewerkend voorwerp: gisteren", "onderwerp: de docent; naamwoordelijk gezegde: gaf uitleg"], "onderwerp: de docent; gezegde: gaf; meewerkend voorwerp: de leerling; lijdend voorwerp: extra uitleg; bijwoordelijke bepaling: gisteren"],
    ["Welke volledige ontleding is correct voor ‘De resultaten werden door de onderzoekers zorgvuldig geanalyseerd.’?", ["onderwerp: de resultaten; werkwoordelijk gezegde: werden geanalyseerd; handelend voorwerp: door de onderzoekers; bijwoordelijke bepaling: zorgvuldig", "onderwerp: de onderzoekers; gezegde: werden; lijdend voorwerp: de resultaten", "onderwerp: zorgvuldig; naamwoordelijk gezegde: werden geanalyseerd", "onderwerp: de resultaten; meewerkend voorwerp: de onderzoekers"], "onderwerp: de resultaten; werkwoordelijk gezegde: werden geanalyseerd; handelend voorwerp: door de onderzoekers; bijwoordelijke bepaling: zorgvuldig"],
    ["Welke volledige ontleding is correct voor ‘Het blijft onzeker of de maatregel voldoende effect heeft.’?", ["voorlopig onderwerp: het; naamwoordelijk gezegde: blijft onzeker; werkelijk onderwerp: of de maatregel voldoende effect heeft", "onderwerp: de maatregel; werkwoordelijk gezegde: blijft", "lijdend voorwerp: effect; gezegde: heeft", "onderwerp: onzeker; naamwoordelijk deel: het"], "voorlopig onderwerp: het; naamwoordelijk gezegde: blijft onzeker; werkelijk onderwerp: of de maatregel voldoende effect heeft"],
    ["Welke zin bevat een extrapositie met voorlopig onderwerp?", ["Het is waarschijnlijk dat de prijzen stijgen.", "Dat de prijzen stijgen, is waarschijnlijk.", "De prijzen stijgen waarschijnlijk.", "Waarschijnlijk stijgen de prijzen."], "Het is waarschijnlijk dat de prijzen stijgen."],
    ["Welke zin bevat een passieve constructie zonder handelend voorwerp?", ["Er werd langdurig overlegd.", "De commissie overlegde langdurig.", "Het overleg was langdurig.", "Door de commissie werd langdurig overlegd."], "Er werd langdurig overlegd."],
    ["Welke zin bevat een naamwoordelijk gezegde én een onderwerpszin?", ["Dat de hypothese klopt, lijkt waarschijnlijk.", "Men denkt dat de hypothese klopt.", "Omdat de hypothese klopt, volgt publicatie.", "De hypothese die klopt wordt gepubliceerd."], "Dat de hypothese klopt, lijkt waarschijnlijk."],
    ["Welke bijzin is een naamwoordelijk-deelzin?", ["De conclusie is dat de aanpak werkt.", "Men concludeert dat de aanpak werkt.", "Dat de aanpak werkt, is duidelijk.", "De aanpak die werkt wordt gekozen."], "De conclusie is dat de aanpak werkt."],
    ["Welke zin bevat een lijdend-voorwerpszin?", ["De commissie betwijfelt of de gegevens volledig zijn.", "Of de gegevens volledig zijn, blijft onduidelijk.", "De gegevens die volledig zijn worden gebruikt.", "Omdat de gegevens volledig zijn, volgt publicatie."], "De commissie betwijfelt of de gegevens volledig zijn."],
    ["Welke zin bevat een bijwoordelijke bijzin van beperking?", ["Voor zover we weten, zijn de gegevens correct.", "Omdat we het weten, zijn de gegevens correct.", "Hoewel we het weten, zijn de gegevens correct.", "Nadat we het weten, zijn de gegevens correct."], "Voor zover we weten, zijn de gegevens correct."],
    ["Welke zin bevat een bijwoordelijke bijzin van verhouding?", ["Naarmate de temperatuur stijgt, neemt de druk toe.", "Omdat de temperatuur stijgt, neemt de druk toe.", "Hoewel de temperatuur stijgt, neemt de druk af.", "Voordat de temperatuur stijgt, meten we de druk."], "Naarmate de temperatuur stijgt, neemt de druk toe."],
    ["Welke zin bevat een correct opgebouwde beknopte bijzin?", ["Na alle bronnen te hebben vergeleken, formuleerde de onderzoeker een conclusie.", "Na alle bronnen te hebben vergeleken, werd een conclusie duidelijk.", "Lopend naar huis, begon de regen.", "Om sneller te werken, werd de computer vastgelopen."], "Na alle bronnen te hebben vergeleken, formuleerde de onderzoeker een conclusie."],
    ["Welke zin bevat een foutieve congruentie?", ["Een groep leerlingen hebben de opdracht gemaakt.", "Een groep leerlingen heeft de opdracht gemaakt.", "De leerlingen hebben de opdracht gemaakt.", "Elke leerling heeft de opdracht gemaakt."], "Een groep leerlingen hebben de opdracht gemaakt."],
    ["Welke zin bevat een tangconstructie die de leesbaarheid vermindert?", ["De commissie heeft, ondanks eerdere bezwaren van meerdere experts en na langdurig intern overleg, het voorstel goedgekeurd.", "Na overleg keurde de commissie het voorstel goed.", "De commissie keurde het voorstel gisteren goed.", "Het voorstel werd goedgekeurd."], "De commissie heeft, ondanks eerdere bezwaren van meerdere experts en na langdurig intern overleg, het voorstel goedgekeurd."],
    ["Welke herschrijving maakt de tangconstructie het duidelijkst?", ["Na langdurig overleg keurde de commissie het voorstel goed, ondanks eerdere bezwaren van experts.", "De commissie heeft het voorstel, dat bezwaren had, na overleg goedgekeurd.", "Het voorstel heeft de commissie goedgekeurd na bezwaren.", "Ondanks heeft de commissie goedgekeurd."], "Na langdurig overleg keurde de commissie het voorstel goed, ondanks eerdere bezwaren van experts."],
    ["Welke zin gebruikt een verwijswoord ondubbelzinnig?", ["Sara sprak met Noor nadat Noor de docent had gebeld.", "Sara sprak met Noor nadat ze de docent had gebeld.", "Nadat ze belde, sprak ze met haar.", "Sara zei haar dat ze kwam."], "Sara sprak met Noor nadat Noor de docent had gebeld."],
    ["Welke analyse van ‘Men noemt deze methode betrouwbaar’ is correct?", ["lijdend voorwerp: deze methode; bepaling van gesteldheid: betrouwbaar", "naamwoordelijk gezegde: noemt betrouwbaar", "meewerkend voorwerp: deze methode", "bijwoordelijke bepaling: betrouwbaar"], "lijdend voorwerp: deze methode; bepaling van gesteldheid: betrouwbaar"],
    ["Welke analyse van ‘Deze methode wordt betrouwbaar genoemd’ is correct?", ["onderwerp: deze methode; werkwoordelijk gezegde: wordt genoemd; bepaling van gesteldheid: betrouwbaar", "naamwoordelijk gezegde: wordt betrouwbaar", "lijdend voorwerp: deze methode", "handelend voorwerp: betrouwbaar"], "onderwerp: deze methode; werkwoordelijk gezegde: wordt genoemd; bepaling van gesteldheid: betrouwbaar"],
    ["Welke zin combineert een betrekkelijke bijzin, een passieve vorm en een handelend voorwerp?", ["Het rapport dat gisteren verscheen werd door drie experts gecontroleerd.", "Omdat het rapport verscheen, controleerden experts het.", "Het rapport verscheen en experts controleerden het.", "De experts die controleerden publiceerden het rapport."], "Het rapport dat gisteren verscheen werd door drie experts gecontroleerd."],
  ],
];

export function generateTaalbeschouwing(
  level: number,
  _random: Random
): ExerciseInput[] {
  const safeLevel = Math.max(1, Math.min(10, Math.round(level || 1)));
  const category = `Taalbeschouwing · niveau ${safeLevel}`;

  return levels[safeLevel - 1].map(([question, options, answer]) =>
    mc(category, question, [...options], answer)
  );
}
