import { NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import { getBuiltInService, normalizeService } from "@/lib/webshopService";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const clean=(v:unknown)=>String(v??"").trim();
export async function POST(request:Request){try{const body=await request.json();const db=getSupabaseAdmin();const serviceId=clean(body.serviceId); const slug=clean(body.slug); let data:any=null; let error:any=null; if(!serviceId.startsWith("builtin:")){const result=await db.from("services").select("*").eq("id",serviceId).eq("is_visible",true).maybeSingle();data=result.data;error=result.error;} const s=data?normalizeService(data):getBuiltInService(slug||serviceId.replace(/^builtin:/,"")); if(!s)return NextResponse.json({error:"Product niet gevonden."},{status:404});const participants=Array.isArray(body.participants)?body.participants:[];const bookingType=body.bookingType==="group"?"group":"individual";const deliveryType=body.deliveryType==="home"?"home":"digital";const count=bookingType==="group"?participants.length:1;if(count<s.min_participants||count>s.max_participants)return NextResponse.json({error:"Ongeldig aantal deelnemers."},{status:400});if(deliveryType==="home"&&!s.allows_home)return NextResponse.json({error:"Begeleiding aan huis is niet beschikbaar."},{status:400});if(deliveryType==="home"&&!clean(body.customerAddress))return NextResponse.json({error:"Adres ontbreekt."},{status:400});const unit=bookingType==="group"?(s.price_per_participant??s.price):s.price;const total=Math.round(unit*count*100)/100;const checkoutId=randomUUID();
 const appointment=s.product_type==="appointment"||s.allows_group;
 let appointmentOrderId="";
 if(appointment){const ins=await db.from("appointment_orders").insert({checkout_id:checkoutId,booking_type:bookingType,education_level:s.education_level,appointment_type:s.title,duration_minutes:60,participant_count:count,price_per_participant:unit,total_amount:total,delivery_type:deliveryType,purchaser_first_name:clean(body.purchaserFirstName),purchaser_last_name:clean(body.purchaserLastName),purchaser_email:clean(body.purchaserEmail).toLowerCase(),purchaser_phone:clean(body.purchaserPhone),purchaser_address:deliveryType==="home"?clean(body.customerAddress):null,customer_address:deliveryType==="home"?clean(body.customerAddress):null,payment_status:"open",booking_status:"awaiting_payment",service_id:s.id.startsWith("builtin:")?null:s.id,service_slug:s.slug}).select("id").single();if(ins.error)throw ins.error;appointmentOrderId=String(ins.data.id);if(participants.length){const rows=participants.map((p:any)=>({order_id:appointmentOrderId,first_names:clean(p.firstNames),last_names:clean(p.lastNames),birth_date:clean(p.birthDate)||null,education_level:s.education_level,grade:clean(p.grade),study_program:clean(p.studyProgram)||null,school:clean(p.school)||null,learning_goal:clean(p.learningGoal)||null,parent_first_name:clean(p.parentFirstName),parent_last_name:clean(p.parentLastName),parent_email:clean(p.parentEmail).toLowerCase(),parent_phone:clean(p.parentPhone)}));const pi=await db.from("appointment_order_participants").insert(rows);if(pi.error)throw pi.error;}}
 const key=clean(process.env.MOLLIE_API_KEY);const base=clean(process.env.NEXT_PUBLIC_SITE_URL)||new URL(request.url).origin;if(!key)throw new Error("MOLLIE_API_KEY ontbreekt.");const metadata=appointment?{orderType:"appointment",appointmentOrderId,checkoutId,bookingType,educationLevel:s.education_level,deliveryType,participantCount:count,purchaserEmail:clean(body.purchaserEmail),serviceSlug:s.slug}:{orderType:"webshop",checkoutId,product:s.slug,productName:s.title,amount:total.toFixed(2),originalAmount:total.toFixed(2),parentName:`${clean(body.purchaserFirstName)} ${clean(body.purchaserLastName)}`.trim(),email:clean(body.purchaserEmail),phone:clean(body.purchaserPhone),paymentMethod:"mollie",isFreeOrder:false};
 const mr=await fetch("https://api.mollie.com/v2/payments",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({amount:{currency:"EUR",value:total.toFixed(2)},description:s.title,redirectUrl:`${base}/betaling/status?checkoutId=${encodeURIComponent(checkoutId)}`,webhookUrl:`${base}/api/mollie/webhook`,metadata})});const mp=await mr.json();if(!mr.ok)throw new Error(mp.detail||"Mollie-betaling kon niet worden aangemaakt.");if(appointment)await db.from("appointment_orders").update({mollie_payment_id:mp.id}).eq("id",appointmentOrderId);else await db.from("webshop_payments").insert({payment_id:mp.id,status:mp.status??"open",metadata});return NextResponse.json({success:true,checkoutUrl:mp._links?.checkout?.href,checkoutId});}catch(e){console.error(e);return NextResponse.json({error:e instanceof Error?e.message:"Checkout mislukt."},{status:500});}}
