"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Mailbox={id:string;internal_email:string;display_name:string;role:"student"|"admin"};
type Message={id:string;subject:string;body:string;is_read:boolean;created_at:string;sender_id:string;receiver_id:string};
export default function LeerlingMailboxClient(){const supabase=useMemo(()=>createClient(),[]);const [box,setBox]=useState<Mailbox|null>(null),[admins,setAdmins]=useState<Mailbox[]>([]),[messages,setMessages]=useState<Message[]>([]),[selected,setSelected]=useState<Message|null>(null),[receiver,setReceiver]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data:own,error:e}=await supabase.from("internal_mailboxes").select("*").eq("user_id",user.id).maybeSingle();if(e||!own){setLoading(false);setError("Er is nog geen mailbox gekoppeld aan dit account.");return}setBox(own);const [{data:a},{data:m}]=await Promise.all([supabase.from("internal_mailboxes").select("*").neq("id",own.id).order("display_name"),supabase.from("internal_messages").select("*").or(`receiver_id.eq.${own.id},sender_id.eq.${own.id}`).order("created_at",{ascending:false})]);setAdmins(a||[]);setMessages(m||[]);setLoading(false)},[supabase]);
 useEffect(()=>{void load()},[load]);
 async function open(m:Message){setSelected(m);if(box&&m.receiver_id===box.id&&!m.is_read){await supabase.from("internal_messages").update({is_read:true}).eq("id",m.id);setMessages(v=>v.map(x=>x.id===m.id?{...x,is_read:true}:x))}}
 async function send(e:React.FormEvent){e.preventDefault();if(!box||!receiver||!subject.trim()||!body.trim())return;setSending(true);setError("");const {error:e2}=await supabase.from("internal_messages").insert({sender_id:box.id,receiver_id:receiver,subject:subject.trim(),body:body.trim(),is_read:false});if(e2)setError(e2.message);else{setSubject("");setBody("");await load()}setSending(false)}
 async function remove(id:string){if(!confirm("Bericht verwijderen?"))return;const {error:e}=await supabase.from("internal_messages").delete().eq("id",id);if(e)setError(e.message);else{setSelected(null);setMessages(v=>v.filter(x=>x.id!==id))}}
 if(loading)return <main className="mailbox-page"><div className="mailbox-empty-card">Mailbox laden…</div></main>;
 if(!box)return <main className="mailbox-page"><div className="mailbox-empty-card"><h1>Mailbox niet gevonden</h1><p>{error}</p></div></main>;
 const unread=messages.filter(m=>m.receiver_id===box.id&&!m.is_read).length;
 return <main className="mailbox-page"><section className="mailbox-hero"><p className="eyebrow">Studio SaGo Mail</p><h1>{box.role==="admin"?"Interne mailbox":"Mijn mailbox"}</h1><p><strong>{box.role==="admin"?"sara.goossens@studiosago.be":box.internal_email}</strong> · {unread} ongelezen</p>{box.role==="admin"&&<p>Alias: creativestudiosago@gmail.be</p>}</section>{error&&<p className="webshop-message webshop-message-error">{error}</p>}<section className="mailbox-grid"><form className="mailbox-compose" onSubmit={send}><h2>Nieuw bericht</h2><label>Naar<select value={receiver} onChange={e=>setReceiver(e.target.value)} required><option value="">Kies ontvanger</option>{admins.map(a=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select></label><label>Onderwerp<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label><label>Bericht<textarea value={body} onChange={e=>setBody(e.target.value)} rows={8} required/></label><button disabled={sending}>{sending?"Verzenden…":"Versturen"}</button></form><section className="mailbox-inbox"><div className="mailbox-heading"><h2>Berichten</h2><button type="button" onClick={()=>void load()}>Vernieuwen</button></div>{messages.length===0?<p className="empty-mailbox">Nog geen berichten.</p>:<div className="mail-list">{messages.map(m=><button type="button" key={m.id} className={`mail-card ${!m.is_read&&m.receiver_id===box.id?"unread":""}`} onClick={()=>void open(m)}><div><h3>{m.subject}</h3><span>{new Date(m.created_at).toLocaleString("nl-BE")}</span></div><p>{m.body.slice(0,120)}{m.body.length>120?"…":""}</p><small>{m.sender_id===box.id?"Verzonden":"Ontvangen"}</small></button>)}</div>}</section></section>{selected&&<div className="mail-modal-backdrop" onClick={()=>setSelected(null)}><article className="mail-modal" onClick={e=>e.stopPropagation()}><button className="mail-close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">{selected.sender_id===box.id?"Verzonden":"Ontvangen"}</p><h2>{selected.subject}</h2><small>{new Date(selected.created_at).toLocaleString("nl-BE")}</small><p className="mail-body">{selected.body}</p><div className="mail-actions"><button onClick={()=>{setReceiver(selected.sender_id===box.id?selected.receiver_id:selected.sender_id);setSubject(`Re: ${selected.subject}`);setSelected(null)}}>Beantwoorden</button><button className="danger" onClick={()=>void remove(selected.id)}>Verwijderen</button></div></article></div>}</main>}
